spring.application.name=quickcart
server.port=8080
# Database (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/quickcartdb
spring.datasource.username=postgres
spring.datasource.password=Vaibhav@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JWT
app.jwt.secret=this-is-a-dev-secret-change-me-please-32bytes
app.jwt.expiration-minutes=60

# Optional: enable admin registration only when this secret is set.
# Example: app.admin.registration.code=some-strong-secret

# OAuth2 Google login
app.oauth2.redirect-uri=http://localhost:5173/auth/oauth2/callback
spring.security.oauth2.client.registration.google.client-id=1013057139407-tfo1853616h3heh3i03qjdetak3n2t5f.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email

app.admin.registration.code=QuickCart
# Logging configuration
logging.level.org.springframework=INFO
logging.level.com.quickcart=DEBUG

# Cloudinary
cloudinary.cloud-name=djrrz3rjp
cloudinary.api-key=287995377371378
cloudinary.api-secret=rjlMLfWRsI3jVTta288k81vb69k

